# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCountCache',
            fields=[
                ('count', models.PositiveIntegerField()),
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
