# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TweetCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
                ('tweets', models.ManyToManyField(to='api.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetCountCache',
            fields=[
                ('count', models.PositiveIntegerField()),
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
