# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170113_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='', max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='', max_length=21),
            preserve_default=False,
        ),
    ]
