# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170113_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='rumor_ration',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
